### ISSUE TITLE
shall we include quantum Fourier Trafo in package?

### ISSUE THREAD

**Issue by urbach** [HISKP-LQCD/qsimulatR#3]
see `vignettes/qft.Rmd`

**Comment by j-ostmeyer** [comment]
Very nice that it works for the general case now!
Yes, I would say that we should include it. It makes the package much more powerful for external users should we publish it. And I don't think it harms much that the students can see an R-implementation and not only pseudo-code. The interesting part will be to implement something like breaking RSA that requires the qft but where the qft itself is not the challenging part.

**Comment by urbach** [comment]
> Very nice that it works for the general case now!
> Yes, I would say that we should include it. It makes the package
> much more powerful for external users should we publish it. And I
> don't think it harms much that the students can see an
> R-implementation and not only pseudo-code. The interesting part will
> be to implement something like breaking RSA that requires the qft
> but where the qft itself is not the challenging part. 

okay, agreed. I have an even more general version, see
phase_estimation.Rmd, which works on a sub-set of the qubits. The
phase estimation doesn't work yet, though...

**Comment by j-ostmeyer** [comment]
It does now.

**Comment by urbach** [comment]
> It does now.

Of course, the 2 pi... The order I had also realised already. thanks.

it does not work for general alpha, though, because then we don't get a product state, still a bit confused.

**Comment by j-ostmeyer** [comment]
It did. 4 digits just don't allow precise results because only two of them are really reliable. I added a few comments.

**Comment by urbach** [comment]
Let's discuss that in person...
-- 
CU Mobil, www.carsten-urbach.eu

**Comment by urbach** [comment]
I think the measurement was still wrong. Now it should be the correct
projective measurement.

Maybe we also need a version of `measure` which measures a range of
qubits. Currently its only either a single one or the whole state.
