### ISSUE TITLE
Measurement done only once

### ISSUE THREAD

**Issue by j-ostmeyer** [HISKP-LQCD/qsimulatR#7]
Do we want to add a function that performs N measurements and instead of a state returns the distribution?
See README.md for a simple example using replicate.

**Comment by urbach** [comment]
> Do we want to add a function that performs N measurements and instead of a state returns the distribution?
> See README.md for a simple example using replicate.

would be good to have!

**Comment by j-ostmeyer** [comment]
Ok, I will push something by tomorrow.

**Comment by j-ostmeyer** [comment]
Multiple measurements are supported now. Still have to add histogram function.

**Comment by urbach** [comment]
now phase_estimation.Rmd fails in `devtools::check`, I'll see what goes wrong.

**Comment by j-ostmeyer** [comment]
That was to be expected. As we discussed, the compatibility changed.

**Comment by j-ostmeyer** [comment]
Once I'm done with the histograms, I will go over the vignettes and adapt the new versions. There will be quite some simplifications.

**Comment by j-ostmeyer** [comment]
Should all be fine now.

**Comment by urbach** [comment]
> Should all be fine now.

apart from some warnings when running the check... I have fixed it.
