### ISSUE TITLE
Output by export2qiskit does not run

### ISSUE THREAD

**Issue by j-ostmeyer** [HISKP-LQCD/qsimulatR#8]
The measurement structures of Qiskit and qsimulatR are very different. For Qiskit you always need to define classical bits in addition to the qubits to store the measurement there. A circuit with zero classical bits, as is required by default in `export2qiskit`, therefore cannot be generated and gives an error.
We should really think twice if we want to support this export. If so, we will have to do quite some tricky stuff in order to realise the measurements.

**Comment by j-ostmeyer** [comment]
Ok, maybe it's not as bad as I thought. One simply has to keep in mind that only measured circuits can be exported. See deutsch-josza vignette.
The example in `qsimulat.Rmd` does not run.

**Comment by urbach** [comment]
> Ok, maybe it's not as bad as I thought. One simply has to keep in mind that only measured circuits can be exported. See deutsch-josza vignette.
> The example in `qsimulat.Rmd` does not run.

does not run where? In Quiskit?

**Comment by j-ostmeyer** [comment]
Yes:
```
>>> qc = QuantumCircuit(2,0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/Johann/anaconda3/envs/name_of_my_env/lib/python3.9/site-packages/qiskit/circuit/quantumcircuit.py", line 171, in __init__
    self.add_register(*regs)
  File "/home/Johann/anaconda3/envs/name_of_my_env/lib/python3.9/site-packages/qiskit/circuit/quantumcircuit.py", line 913, in add_register
    regs = (QuantumRegister(regs[0], 'q'), ClassicalRegister(regs[1], 'c'))
  File "/home/Johann/anaconda3/envs/name_of_my_env/lib/python3.9/site-packages/qiskit/circuit/register.py", line 47, in __init__
    raise CircuitError("Register size must be positive (%s '%s' was provided)"
qiskit.circuit.exceptions.CircuitError: "Register size must be positive (int '0' was provided)"
```

**Comment by urbach** [comment]
okay, my bad. If the number of classical bits is zero, one needs to drop the second argument. I'll fix that...
> Yes:
> ```
> >>> qc = QuantumCircuit(2,0)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/Johann/anaconda3/envs/name_of_my_env/lib/python3.9/site-packages/qiskit/circuit/quantumcircuit.py", line 171, in __init__
>     self.add_register(*regs)
>   File "/home/Johann/anaconda3/envs/name_of_my_env/lib/python3.9/site-packages/qiskit/circuit/quantumcircuit.py", line 913, in add_register
>     regs = (QuantumRegister(regs[0], 'q'), ClassicalRegister(regs[1], 'c'))
>   File "/home/Johann/anaconda3/envs/name_of_my_env/lib/python3.9/site-packages/qiskit/circuit/register.py", line 47, in __init__
>     raise CircuitError("Register size must be positive (%s '%s' was provided)"
> qiskit.circuit.exceptions.CircuitError: "Register size must be positive (int '0' was provided)"
> ```
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/HISKP-LQCD/qsimulatR/issues/8#issuecomment-724656703

-- 
Carsten Urbach
e-mail: curbach@gmx.de
        urbach@hiskp.uni-bonn.de
Fon   : +49 (0)228 73 2379
skype : carsten.urbach
URL: http://www.carsten-urbach.eu

**Comment by urbach** [comment]
should be fixed now!

**Comment by j-ostmeyer** [comment]
Thanks! That was easier than I expected.
I will see if I can find any other edge cases...

**Comment by urbach** [comment]
> Thanks! That was easier than I expected.
> I will see if I can find any other edge cases...

There are other edge cases, for instance for self-defined gates...

**Comment by j-ostmeyer** [comment]
Sure. But I guess we are not going to include them, do we? They do not run on a real quantum computer.

**Comment by j-ostmeyer** [comment]
We should make the export throw an error in these cases though. Now it just prints something and this something does not run with Qiskit.

**Comment by j-ostmeyer** [comment]
I'm happy with the function now.
